"""
    The wordlist module lists around 1000 easy, medium, and hard level words
    for word games.

    Tyler
    6/2/24
"""


# Annotate the variables.
easy_words = list[str]
medium_words = list[str]
hard_words: list[str]


# List easy mode hangman words.
easy_words = [
    "ant", "apple", "arm", "baby", "bag", "ball", "bat", "bear", "bed", "bee", "bell", "bird", 
    "book", "boy", "bread", "bus", "cake", "car", "cat", "chair", "chick", "clock", "cloud", 
    "coat", "cow", "cup", "dog", "doll", "door", "duck", "ear", "egg", "elephant", "eye", 
    "farm", "fish", "flower", "foot", "frog", "game", "girl", "goat", "grape", "grass", "hat", 
    "head", "hen", "hill", "home", "horse", "house", "jam", "jar", "jet", "kite", "leg", 
    "lemon", "lion", "man", "map", "milk", "moon", "mouse", "nest", "nose", "nut", "pan", 
    "pen", "pencil", "pig", "pot", "rain", "rat", "ring", "road", "rock", "rose", "rug", 
    "sand", "seed", "sheep", "shirt", "shoe", "shop", "snow", "sock", "sun", "table", "toy", 
    "tree", "truck", "tub", "van", "water", "zoo", "air", "angel", "bagel", "bead", "beach", 
    "bean", "bee", "bell", "belt", "bike", "bird", "boat", "book", "boot", "brush", "bush", 
    "cake", "camp", "cart", "carrot", "chalk", "chimp", "clay", "cliff", "clown", "cob", 
    "corn", "couch", "crab", "crib", "crown", "cub", "deer", "dice", "dirt", "dish", "dog", 
    "doll", "dove", "dune", "ear", "elf", "fence", "fin", "flag", "flame", "flap", "flock", 
    "flood", "flour", "flute", "foam", "fog", "foil", "foot", "fork", "fox", "frog", "fruit", 
    "fry", "gale", "game", "gap", "gate", "gear", "germ", "gift", "goat", "grape", "grill", 
    "hat", "heel", "hip", "hop", "hose", "hunt", "hut", "ice", "ink", "ivy", "jam", "jelly", 
    "jump", "kite", "kitten", "knee", "ladle", "lake", "lamb", "lamp", "lane", "leaf", "leap", 
    "leg", "lime", "lizard", "loaf", "log", "malt", "mane", "marble", "mat", "moth", "mouse", 
    "muffin", "mug", "nail", "nap", "nest", "net", "nibble", "nose", "nurse", "nut", "oak", 
    "oar", "orange", "owl", "pail", "pain", "pan", "peach", "pear", "peas", "pen", "pencil", 
    "peony", "pepper", "pet", "pie", "pig", "pill", "pin", "pint", "pit", "plane", "plant", 
    "plow", "plum", "pool", "pot", "puddle", "puff", "quack", "quill", "quiz", "rain", "rat", 
    "reed", "rice", "rock", "roof", "room", "root", "rose", "rug", "sand", "seat", "seed", 
    "shell", "shirt", "shoe", "shop", "shrub", "side", "sink", "skirt", "sled", "sleet", 
    "slime", "smile", "snail", "snake", "sock", "sofa", "soil", "song", "soup", "sow", 
    "spoon", "spot", "squirrel", "star", "stew", "stove", "straw", "stream", "street", 
    "string", "swan", "swing", "table", "taco", "tail", "tank", "tart", "tent", "thorn", 
    "tiger", "tin", "toad", "toast", "tooth", "toy", "trap", "tree", "truck", "tub", "tug", 
    "twig", "vase", "veil", "village", "vine", "wagon", "wail", "wait", "wall", "walnut", 
    "wave", "well", "whale", "wheat", "wheel", "whip", "wind", "wing", "wink", "wire", 
    "wish", "wood", "wool", "worm", "yak", "yawn", "yogurt", "yolk", "zebra", "zip"
]
# List medium mode hangman words.
medium_words = [
    "accordion", "activate", "adult", "aid", "algae", "alternative", "ambulance", "analyze", 
    "ant", "apple", "appointment", "aquarium", "artist", "assignment", "author", "aunt", 
    "avocado", "baby", "backpack", "ball", "balloon", "bandage", "banjo", "banana", "bear", 
    "beach", "beliefs", "bell", "bike", "biology", "blades", "blueberry", "board", "boat", 
    "boots", "brush", "brother", "buffalo", "bus", "butterfly", "cafeteria", "cake", 
    "calculator", "calm", "camp", "cantaloupe", "capsule", "car", "castle", "cat", "cello", 
    "chalk", "chair", "cheese", "chef", "cherry", "child", "choice", "choose", "clarinet", 
    "clarity", "classroom", "cloud", "coach", "compassion", "comprehend", "computer", 
    "concentration", "contentment", "coral", "cousin", "crab", "creativity", "crayon", "dad", 
    "dancer", "date", "desk", "determine", "diet", "dignity", "dinosaur", "discover", 
    "discovery", "dish", "diver", "doctor", "dog", "dolphin", "dragonfruit", "driver", 
    "drought", "drums", "dune", "earring", "easter", "eat", "educate", "education", 
    "elephant", "emergency", "energize", "enlighten", "evaluate", "exercise", "experience", 
    "experiment", "eye", "facts", "faith", "fall", "family", "feather", "field", "fig", 
    "firefighter", "fishing", "fitness", "float", "flute", "focus", "forest", "fork", 
    "friend", "frisbee", "fruit", "full", "game", "goal", "goat", "goggles", "grape", "grass", 
    "guitar", "guava", "gym", "happiness", "hat", "health", "helicopter", "hippopotamus", 
    "holiday", "honeydew", "hope", "hot", "ice", "iguana", "imagination", "information", 
    "injection", "inspiration", "integrity", "interesting", "island", "jacket", "jaguar", 
    "jellyfish", "judge", "jump", "kaleidoscope", "kangaroo", "kayak", "keyboard", "kite", 
    "kiwi", "knowledge", "lake", "lamp", "learn", "lemon", "lesson", "library", "life", "light", 
    "lime", "lion", "lizard", "lobster", "love", "loyalty", "lunch", "lychee", "mailman", 
    "mall", "mandarin", "maraca", "marble", "marine", "market", "marshmallow", "mask", "math", 
    "measure", "meditation", "memory", "mindfulness", "monkey", "moon", "morality", "mother", 
    "mountain", "muffin", "music", "musician", "museum", "mushroom", "necklace", "nectarine", 
    "newt", "niece", "notebook", "nurse", "ocean", "octopus", "olive", "orange", "orchard", 
    "orchestra", "option", "optimism", "orange", "paint", "painter", "pajamas", "panda", 
    "pansy", "papa", "paper", "parent", "park", "parrot", "patient", "pear", "peach", "peacock", 
    "peace", "pen", "pencil", "penguin", "pepper", "perseverance", "pet", "pickle", "pilot", 
    "pillow", "pineapple", "piano", "planet", "plankton", "plant", "plum", "plumber", 
    "police", "pomegranate", "positive", "principles", "puppy", "quail", "quince", "rabbit", 
    "rain", "raincoat", "raisins", "raspberry", "recall", "relaxation", "reptile", "rescue", 
    "respect", "retreat", "ribbon", "roller", "rose", "safe", "sailboat", "sand", "saxophone", 
    "school", "scissors", "seaweed", "serenity", "shark", "sheep", "shells", "ship", "shirt", 
    "shoes", "shrimp", "siblings", "sidewalk", "silence", "sister", "skateboard", "snake", 
    "snow", "snowboard", "soap", "soccer", "socks", "solitude", "spaghetti", "spaceship", 
    "star", "strawberry", "study", "summer", "sundae", "sunglasses", "sun", "super", 
    "support", "surfboard", "swim", "symptoms", "table", "tablet", "teacher", "team", 
    "teaspoon", "teeth", "television", "therapy", "thermometer", "thought", "tiger", 
    "toaster", "toboggan", "tomato", "tornado", "towel", "track", "tractor", "train", 
    "tranquility", "trampoline", "treat", "treatment", "tree", "trip", "trombone", "trouble", 
    "trout", "truck", "tuba", "tulip", "tuna", "turtle", "ukulele", "umbrella", "uncle", 
    "understand", "unicycle", "uplift", "vacation", "van", "vegetable", "violin", "vulture", 
    "water", "watermelon", "waves", "wellness", "whale", "window", "wisdom", "wolf", "workout", 
    "xylophone", "yak", "yarn", "yoga", "yogurt", "yellow", "yuzu", "zebra", "zoo", "zucchini"
]

# List hard mode hangman words.
hard_words = [
    "abacus", "abandon", "ability", "absence", "academy", "account", "accuse", "achieve", "acquire",
    "address", "advance", "advice", "affect", "agency", "aircraft", "alcohol", "alert", "allege", 
    "alliance", "allowance", "amazing", "ambition", "analysis", "ancient", "anxiety", "apology", 
    "appeal", "appetite", "applause", "approve", "arbitrary", "archive", "argument", "arise", 
    "arrival", "article", "artwork", "ashamed", "aspect", "assault", "assembly", "athlete", 
    "attempt", "attorney", "attract", "auction", "audience", "autumn", "average", "backbone", 
    "baggage", "balance", "balloon", "banquet", "bargain", "barrier", "batter", "battery", 
    "because", "bedroom", "believe", "beneath", "benefit", "bicycle", "biology", "birthday", 
    "blanket", "blessing", "boiling", "borrow", "bother", "boundary", "bravery", "breadth", 
    "breathe", "briefly", "broaden", "brother", "builder", "burden", "butter", "cabinet", 
    "calculate", "campaign", "cancer", "capital", "capture", "careful", "carpet", "carriage", 
    "carrier", "cartoon", "catalog", "category", "caution", "ceiling", "celebrate", "cemetery", 
    "century", "ceremony", "certain", "chamber", "chance", "change", "channel", "charity", 
    "charming", "checkout", "cheerful", "chemical", "chicken", "choice", "chronic", "circuit", 
    "citizen", "classic", "climate", "closure", "clothing", "coastal", "college", "comfort", 
    "command", "commerce", "commonly", "compete", "complain", "compose", "concern", "concert", 
    "concrete", "conduct", "conflict", "congress", "connect", "consent", "consider", "constant", 
    "consume", "contact", "contain", "content", "contest", "contract", "contrast", "convert", 
    "convey", "convince", "cooking", "correct", "cottage", "council", "counter", "country", 
    "courage", "covered", "crucial", "crystal", "culture", "curtain", "custody", "damaged", 
    "dancer", "daytime", "deadline", "decrease", "default", "defense", "deficit", "deliver", 
    "density", "deposit", "deserve", "design", "despite", "destroy", "detailed", "develop", 
    "device", "diamond", "dialogue", "digital", "diplomat", "disagree", "disaster", "disclose", 
    "disease", "disguise", "dismiss", "disorder", "display", "dispute", "distance", "district", 
    "diverse", "dividend", "divorce", "doctrine", "document", "dominate", "donation", "doorway", 
    "doubtful", "downward", "drawing", "dressed", "driving", "dynamic", "earlier", "earnings", 
    "economy", "edition", "educate", "effort", "elderly", "election", "element", "embassy", 
    "embrace", "emerge", "emphasis", "empire", "employ", "enable", "enclose", "encounter", 
    "endless", "endorse", "endure", "engage", "enhance", "enlarge", "enormous", "episode", 
    "equality", "equation", "equip", "erosion", "escort", "especially", "essence", "establish", 
    "estimate", "eternal", "evaluate", "evening", "evident", "exactly", "examine", "example", 
    "exceed", "excellent", "exchange", "excited", "exclude", "excuse", "exhibit", "existence", 
    "expansion", "expect", "expensive", "experience", "explore", "express", "extend", "extract", 
    "extreme", "facility", "faculty", "failure", "famous", "fantasy", "farmer", "fashion", 
    "favorite", "feature", "federal", "feeling", "festival", "fiction", "fifteen", "fighter", 
    "finally", "finance", "finding", "fishing", "fitness", "flavor", "flexible", "flower", 
    "focused", "forbid", "foreign", "forgive", "formula", "fortune", "forward", "freedom", 
    "frequent", "friendly", "fulfill", "function", "further", "gallery", "garbage", "garden", 
    "garment", "gather", "general", "genetic", "genuine", "gesture", "gigantic", "glacier", 
    "glimpse", "govern", "grateful", "gravity", "greatly", "grocery", "guardian", "guidance", 
    "guilty", "habitat", "harmony", "harvest", "hazard", "healing", "healthy", "hearing", 
    "heavily", "heritage", "highway", "history", "holiday", "honesty", "horizon", "horrible", 
    "hostile", "household", "housing", "however", "humble", "hundred", "hunger", "hungry", 
    "hygiene", "identify", "illness", "illegal", "illusion", "illustrate", "imagine", "immediate", 
    "immense", "immune", "impact", "impose", "impress", "improve", "include", "income", "increase", 
    "indicate", "indirect", "indoor", "infamous", "infinite", "informal", "inherit", "inhibit", 
    "initial", "injury", "inquiry", "insight", "install", "instant", "instead", "instruct", 
    "insure", "integral", "intense", "interact", "interest", "interior", "interval", "intimate", 
    "involve", "isolate", "journal", "journey", "justice", "justify", "kingdom", "kitchen", 
    "knowing", "landing", "landscape", "laughter", "lawmaker", "leading", "learning", "leather", 
    "lecture", "leisure", "length", "liberty", "library", "license", "lighter", "likely", 
    "limited", "literary", "location", "logical", "loyalty", "machine", "madness", "magazine", 
    "maintain", "majority", "manager", "mankind", "mansion", "marginal", "marriage", "massive", 
    "material", "maximum", "meaning", "measure", "medical", "meeting", "mention", "merchant", 
    "message", "metallic", "million", "minimal", "ministry", "miracle", "misery", "missing", 
    "mission", "mistake", "mixture", "mobile", "modern", "moment", "monitor", "monster", 
    "monthly", "morning", "mother", "motion", "motive", "mountain", "mystery", "narrative", 
    "narrow", "national", "nature", "nearby", "necessary", "negative", "neglect", "neither", 
    "nervous", "network", "neutral", "newspaper", "nobody", "nominate", "nonprofit", "notable", 
    "nothing", "nowhere", "nuclear", "numerous", "observe", "obstacle", "obvious", "offense", 
    "officer", "official", "ongoing", "operate", "opinion", "oppose", "optical", "option", 
    "orchard", "organic", "outcome", "outdoor", "outline", "outrage", "outside", "overcome", 
    "overhead", "overlook", "overseas", "overview", "ownership", "oxidize", "package", "painting", 
    "paradise", "parallel", "partial", "partner", "passage", "patient", "pattern", "payment", 
    "peaceful", "penalty", "pension", "percent", "perfect", "perform", "perhaps", "permanent", 
    "personal", "persuade", "petroleum", "pharmacy", "photograph", "physical", "pioneer", 
    "plastic", "pleasure", "popular", "portion", "portrait", "position", "positive", "possible", 
    "postpone", "pottery", "poverty", "practice", "precise", "predict", "prefer", "prepare", 
    "presence", "preserve", "president", "pressing", "pretend", "prevent", "primary", "princess", 
    "printer", "private", "problem", "proceed", "process", "produce", "profound", "program", 
    "project", "promote", "protect", "provide", "public", "publish", "purpose", "pursue", 
    "qualify", "quality", "quarter", "question", "quickly", "quietly", "radical", "rainfall", 
    "random", "rapidly", "realistic", "reality", "realize", "receipt", "receive", "recover", 
    "recruit", "recycle", "reflect", "reform", "refresh", "refuse", "regard", "register", 
    "regulate", "reinforce", "reject", "relate", "release", "relief", "remain", "remedy", 
    "remember", "remind", "remove", "renowned", "repair", "replace", "request", "require", 
    "rescue", "research", "resemble", "resident", "resist", "resolve", "resource", "respect", 
    "respond", "restore", "restrain", "result", "retail", "retain", "retire", "reveal", 
    "revenge", "reverse", "revise", "reward", "rhetoric", "rhythm", "ridiculous", "routine", 
    "ruin", "sacred", "salary", "sanction", "satisfy", "science", "sculpture", "season", 
    "section", "segment", "sentence", "sequence", "settle", "shadow", "shortage", "shrimp", 
    "silence", "sincere", "situate", "sketch", "skillful", "slavery", "slogan", "smooth", 
    "society", "software", "soldier", "solution", "somehow", "source", "special", "species", 
    "spectrum", "sponsor", "sports", "station", "status", "storage", "strange", "strategy", 
    "stretch", "student", "subject", "succeed", "sudden", "suffer", "suggest", "summary", 
    "sunshine", "support", "surface", "surgery", "surprise", "surround", "survey", "survival", 
    "suspect", "suspend", "sweater", "symbol", "sympathy", "talented", "taxpayer", "teacher", 
    "teaspoon", "teenager", "tension", "terrain", "theater", "therapy", "thought", "tightly", 
    "tobacco", "together", "tolerate", "tomorrow", "tornado", "tourism", "traffic", "transform", 
    "transition", "translate", "transport", "treasure", "treaty", "triumph", "trouble", "trustee", 
    "twelve", "typical", "ultimate", "unaware", "unbroken", "undergo", "undertake", "uniform", 
    "unique", "universal", "unknown", "unlawful", "unlimited", "unusual", "upcoming", "upgrade", 
    "upstairs", "urban", "urgency", "usage", "usually", "utility", "vacation", "validity", 
    "valuable", "vaccine", "vampire", "variety", "vehicle", "venture", "verdict", "versus", 
    "veteran", "victory", "village", "violence", "virtual", "visible", "visitor", "visual", 
    "vitamin", "volcano", "volunteer", "vulnerable", "warrior", "wealthy", "weather", "webmaster", 
    "welfare", "whenever", "wherever", "whisper", "whistle", "widespread", "wildlife", "willing", 
    "withdraw", "wonderful", "wooden", "worship", "worthy", "writing", "yearly", "yellow", 
    "yourself", "youthful", "zealous", "zebra", "zephyr"
]

